#!/bin/sh
# Bake all fetch()-loaded data + assets into data/embedded-data.js so the site
# runs with NO server (double-click opening.html). Re-run after editing any
# file in data/ or assets/cache/ or the fetched SVGs in assets/ui/.
#
# Uses Node only to JSON-escape file contents safely (Hebrew, quotes, newlines).
set -e
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

if ! command -v node >/dev/null 2>&1; then
  echo "ERROR: node is required to build the embedded data file." >&2
  exit 1
fi

# Files served via fetch() at runtime. Keep in sync with the fetch() calls in
# js/ (data pipeline, opening palette, word-cluster + meso caches, layer-nav SVGs).
FILES="
data/main.csv
data/tags.csv
data/opening-palette.json
assets/cache/word-clusters.json
assets/cache/meso-silhouettes.json
assets/ui/layer-nav-l1.svg
assets/ui/layer-nav-blocks.svg
assets/ui/layer-nav-marker.svg
"

FILES="$FILES" ROOT="$ROOT" node - <<'NODE'
const fs = require('fs');
const path = require('path');

const root = process.env.ROOT;
const files = process.env.FILES.split('\n').map(s => s.trim()).filter(Boolean);

let out = '';
out += '/* AUTO-GENERATED by build-embedded-data.sh — do not edit by hand.\n';
out += '   Baked copies of every file the site loads via fetch(), so it runs\n';
out += '   with no server (double-click opening.html). Read by js/offline-data-shim.js. */\n';
out += 'window.__EMBEDDED_DATA__ = window.__EMBEDDED_DATA__ || {};\n';

let count = 0;
let bytes = 0;
for (const rel of files) {
  const abs = path.join(root, rel);
  if (!fs.existsSync(abs)) {
    console.warn('  skip (missing): ' + rel);
    continue;
  }
  const content = fs.readFileSync(abs, 'utf8');
  bytes += Buffer.byteLength(content, 'utf8');
  out += 'window.__EMBEDDED_DATA__[' + JSON.stringify(rel) + '] = ' + JSON.stringify(content) + ';\n';
  count++;
}

const dest = path.join(root, 'data', 'embedded-data.js');
fs.writeFileSync(dest, out, 'utf8');
console.log('Built data/embedded-data.js — ' + count + ' files, ' + (bytes / 1024).toFixed(0) + ' KB embedded.');
NODE
